package org.milab.dataMining.ICTCLAS;

/**
 * A general interface for result generated by wrapper. Not sure what which
 * attributes should be expose, I just use all available in ICTCLAS50.
 * 
 * @author Guoquan
 * 
 */
public interface ICTCLASResult {
	/**
	 * Get byte-wise start position of split word
	 */
	public int getByteStart();

	/**
	 * Get byte-wise word length of split word
	 */
	public int getByteLength();

	/**
	 * Get pos string of word
	 */
	public String getPosStr();

	/**
	 * Get pos id of word
	 */
	public int getPosId();

	/**
	 * Get word id
	 */
	public int getWordId();

	/**
	 * Get whether this is a word from user dictionary
	 */
	public boolean isUserDict();

	/**
	 * Get weight of word
	 */
	public int getWeight();
}
